- pom.xml
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es7/ES7IndexPreparer.java
- src/main/resources/freemarker/es7x/alias/alias.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-health.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-monitor.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
**Issue**
https://github.com/gravitee-io/issues/issues/7110
Use new methods introduced with https://github.com/gravitee-io/gravitee-common-elasticsearch/pull/173 to handle alias creation in ILM mode.
A new index with an alias is created if and only if alias does not exist yet.
Also added a missing field in index-templates to make ILM works
---
- use it directly by updating your project with version: `3.8.5-7110-fix-ILM-support-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/3.8.5-7110-fix-ILM-support-SNAPSHOT/g …
> fix: create index and alias to make ILM works

- README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7110
Add documentation about ILM configuration
---
- use it directly by updating your project with version: `3.12.1`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/3.12.1/gravitee-reporter-elasticsearch-3.12.1.zip)
> Add documentation about ILM configuration + compatibility matrix

- src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- src/main/resources/freemarker/es5x/mapping/index-template.ftl
- src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
**Issue**
https://github.com/gravitee-io/issues/issues/7094
In the [gravitee-reporter-api metrics class](https://github.com/gravitee-io/gravitee-reporter-api/blob/master/src/main/java/io/gravitee/reporter/api/http/Metrics.java#L33) the api response time is a long.
Now let's imagine you create an API on APIM and link it to an endpoint which send events using SSE. If you keep the stream alive for a time ( in millisecond ) greater than the interger max value you can have an error saying.
To reproduce the bug you'll have to wait 3 weeks before closing your http request or play with the time itself 😛
NB: When this pull request will be merge I'll cherry pick the commit to have the fix on all other versions.
```
17:43:51.806 [vert.x-eventloop-thread-10] [] ERROR …
```
> fix: align template api response time type with metrics api response time type

- pom.xml
- src/main/resources/freemarker/es5x/index/health.ftl
- src/main/resources/freemarker/es5x/index/log.ftl
- src/main/resources/freemarker/es6x/index/health.ftl
- src/main/resources/freemarker/es6x/index/log.ftl
- src/main/resources/freemarker/es7x/index/health.ftl
- src/main/resources/freemarker/es7x/index/log.ftl
**Issue**
https://github.com/gravitee-io/issues/issues/7930
Rollback the work that has been done for 
- `health` freemarker template in https://github.com/gravitee-io/gravitee-reporter-elasticsearch/commit/d9f1a91a0536533e709fe5d0657a9ade1b80167a
- `logs` freemarker template in https://github.com/gravitee-io/gravitee-reporter-elasticsearch/commit/baa01473610808a8921059fb7a661dffe252c44b
This changed is due to the work on https://github.com/gravitee-io/issues/issues/7812 which changes the implementations of `HttpHeaders` to also implements `MultiMap` (which is a `Map`).
Freemarker detects the object as `instanceof Map` and apply to him a `DefaultMapAdapter`, making impossible to use the methods from `HttpHeaders` in the template.
Here is a proposal …
> fix: use map iteration style for headers in health and logging

- src/main/resources/freemarker/es5x/index/log.ftl
- src/main/resources/freemarker/es6x/index/log.ftl
- src/main/resources/freemarker/es7x/index/log.ftl
**Issue**
https://github.com/gravitee-io/issues/issues/7930
---
- use it directly by updating your project with version: `3.12.4-issues-7930-fix-es-headers-reporting-2-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/3.12.4-issues-7930-fix-es-headers-reporting-2-SNAPSHOT/gravitee-reporter-elasticsearch-3.12.4-issues-7930-fix-es-headers-reporting-2-SNAPSHOT.zip)
> fix: use map iteration style for headers in logging - missed blocks

- pom.xml
- src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- src/main/java/io/gravitee/reporter/elasticsearch/indexer/name/AbstractPerTypeIndexNameGenerator.java
**Issue**
[APIM-490](https://gravitee.atlassian.net/browse/APIM-490)
Rename path to pathInfo
Rename index to avoid issue with pattern matching
[APIM-490]: https://gravitee.atlassian.net/browse/APIM-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
- use it directly by updating your project with version: `4.1.0-rename-path-to-path-info-in-v4-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.1.0-rename-path-to-path-info-in-v4-SNAPSHOT/gravi …
> Rename path to path info in v4

- pom.xml
Bump common ES version
---
- use it directly by updating your project with version: `4.1.0-bump-common-elasticsearch-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.1.0-bump-common-elasticsearch-version-SNAPSHOT/gravitee-reporter-elasticsearch-4.1.0-bump-common-elasticsearch-version-SNAPSHOT.zip)
> fix: bump common elasticsearch version

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/APIM-490
Use latest alpha version
---
- use it directly by updating your project with version: `4.1.0-bump-common-es-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.1.0-bump-common-es-version-SNAPSHOT/gravitee-reporter-elasticsearch-4.1.0-bump-common-es-version-SNAPSHOT.zip)
> fix: bump common elasticsearch version to 4.1.0-alpha.6

- pom.xml
Description
Adding error status on message metrics.
---
- use it directly by updating your project with version: `4.1.0-apim-490-add-error-metric-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.1.0-apim-490-add-error-metric-SNAPSHOT/gravitee-reporter-elasticsearch-4.1.0-apim-490-add-error-metric-SNAPSHOT.zip)
> fix: bump common elasticsearch version to get new error status

- README.adoc
- pom.xml
- src/main/java/io/gravitee/reporter/elasticsearch/BeanRegister.java
- src/main/java/io/gravitee/reporter/elasticsearch/indexer/es8/ES8BulkIndexer.java
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es8/ES8IndexPreparer.java
- src/main/java/io/gravitee/reporter/elasticsearch/spring/context/Elastic8xBeanRegistrer.java
- src/test/java/io/gravitee/reporter/elasticsearch/BeanRegisterTest.java
- src/test/java/io/gravitee/reporter/elasticsearch/IntegrationTestConfiguration.java
- src/test/java/io/gravitee/reporter/elasticsearch/spring/IndexNameGeneratorRegistrationTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-427
Add ES 8 support
Depends on https://github.com/gravitee-io/gravitee-common-elasticsearch/pull/181
---
- use it directly by updating your project with version: `4.1.0-es8-support-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.1.0-es8-support-SNAPSHOT/gravitee-reporter-elasticsearch-4.1.0-es8-support-SNAPSHOT.zip)
> Add ES 8 support

- pom.xml
---
- use it directly by updating your project with version: `4.1.0-fix-bump-common-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.1.0-fix-bump-common-SNAPSHOT/gravitee-reporter-elasticsearch-4.1.0-fix-bump-common-SNAPSHOT.zip)
> fix: bump common-elasticsearch version

- src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-2575
Read pem certs and keys as a list for ElasticSearch configuration
---
- use it directly by updating your project with version: `4.2.2-APIM-2575-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.2.2-APIM-2575-SNAPSHOT/gravitee-reporter-elasticsearch-4.2.2-APIM-2575-SNAPSHOT.zip)
> Read pem certs and keys as a list for ElasticSearch configuration

- src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-2575
(cherry picked from commit 3de5958b2e9f484a8b238db9f1f58111932610b9)
---
- use it directly by updating your project with version: `4.0.3-apim-2575-es-keystore-config-4-0-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/4.0.3-apim-2575-es-keystore-config-4-0-x-SNAPSHOT/gravitee-reporter-elasticsearch-4.0.3-apim-2575-es-keystore-config-4-0-x-SNAPSHOT.zip)
> fix: read pem certs and keys as a list for ElasticSearch configuration

- pom.xml
---
- use it directly by updating your project with version: `5.0.1-fix-common-dependency-scope-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.0.1-fix-common-dependency-scope-SNAPSHOT/gravitee-reporter-elasticsearch-5.0.1-fix-common-dependency-scope-SNAPSHOT.zip)
> fix: move reporter common dependency scope to compile

- pom.xml
- src/main/java/io/gravitee/reporter/elasticsearch/config/PipelineConfiguration.java
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/AbstractIndexPreparer.java
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es7/ES7IndexPreparer.java
- src/main/java/io/gravitee/reporter/elasticsearch/spring/ElasticsearchReporterConfiguration.java
- src/main/resources/freemarker/geoip.ftl
- src/main/resources/freemarker/gravitee.ftl
- src/main/resources/freemarker/pipeline.ftl
- src/main/resources/freemarker/user_agent.ftl
- src/test/java/io/gravitee/reporter/elasticsearch/config/PipelineConfigurationTest.java
- src/test/resources/logback-test.xml
This has gone unnoticed in the previous version because the common-elasticsearch version was not bumped.
This revision adds the pipeline templates and bumpts common-elasticsearch as well as reporter-common in order to get the freemarker component able to read templates from a parent class loader.
see https://github.com/gravitee-io/gravitee-reporter-common/pull/4
☝️ This should be merged before and this should be amend to bump to the actual reporter-common version
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `5.0.2-fix-common-elasticsearch-version-SNAPSHOT`
- download …
> fix: add ingest pipelines plugins template

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/APIM-3180
Following this [PR](https://github.com/gravitee-io/gravitee-reporter-common/pull/9)
the new version of this reporter will fix the problem in APIM  4.2
---
- use it directly by updating your project with version: `5.0.3-APIM-3180-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.0.3-APIM-3180-SNAPSHOT/gravitee-reporter-elasticsearch-5.0.3-APIM-3180-SNAPSHOT.zip)
> fix: bump gravitee-reporter-common to fix espace issue

- pom.xml
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es8/ES8IndexPreparer.java
- src/main/resources/freemarker/es8x/mapping/index-template-health.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-monitor.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-request.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-message-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-message-metrics.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-metrics.ftl
**Issue**
https://gravitee.atlassian.net/browse/APIM-3014
For ES8, we are now using "new" index template format instead of "legacy" one. 
It's ok for both cases on a fresh installation or an existing one. New templates will be create and ES will use them instead of legacy one.
Require https://github.com/gravitee-io/gravitee-common-elasticsearch/pull/203
---
- use it directly by updating your project with version: `5.1.0-apim3014-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.1.0-apim30 …
> feat: use index template instead of legacy template in ES8

- .github/renovate.json
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `5.1.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.1.0/gravitee-reporter-elasticsearch-5.1.0.zip)
> chore: update renovate configuration to enable automerge on some dependency

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/APIM-4083
https://github.com/gravitee-io/issues/issues/9589
Bump reporter-common to fix Monitor issue
---
- use it directly by updating your project with version: `5.1.3-apim-4083-use-right-monitor-class-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.1.3-apim-4083-use-right-monitor-class-SNAPSHOT/gravitee-reporter-elasticsearch-5.1.3-apim-4083-use-right-monitor-class-SNAPSHOT.zip)
> fix: bump reporter-common for Monitor issue

- pom.xml
- src/main/resources/freemarker/es7x/mapping/index-template-v4-metrics.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-metrics.ftl
**Issue**
https://gravitee.atlassian.net/browse/APIM-3481
---
- use it directly by updating your project with version: `5.2.0-apim-3481-add-entrypoint-id-to-metrics-v4-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.2.0-apim-3481-add-entrypoint-id-to-metrics-v4-SNAPSHOT/gravitee-reporter-elasticsearch-5.2.0-apim-3481-add-entrypoint-id-to-metrics-v4-SNAPSHOT.zip)
> feat: report entrypoint id in v4 metrics index

- pom.xml
- src/main/resources/freemarker/es7x/mapping/index-template-health.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-v4-log.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-v4-message-log.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-v4-message-metrics.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-v4-metrics.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-health.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-request.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-message-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-message-metrics.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-metrics.ftl
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-3932
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `5.4.0-apim-3932-Show-API-name-in-reporters-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.4.0-apim-3932-Show-API-name-in-reporters-SNAPSHOT/gravitee-reporter-elasticsearch-5.4.0-apim-3932-Show-API-name-in-reporters-SNAPSHOT.zip)
> feat: Show API name in reporters

- pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-7146
bump gravitee-reporter-common version
---
- use it directly by updating your project with version: `5.5.2-APIM-7146-bump-gravitee-reporter-common-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.5.2-APIM-7146-bump-gravitee-reporter-common-SNAPSHOT/gravitee-reporter-elasticsearch-5.5.2-APIM-7146-bump-gravitee-reporter-common-SNAPSHOT.zip)
> fix: bump gravitee-reporter-common version

- pom.xml
**Issue**
APIM-9340
---
- use it directly by updating your project with version: `5.8.1-fix-9340-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.8.1-fix-9340-SNAPSHOT/gravitee-reporter-elasticsearch-5.8.1-fix-9340-SNAPSHOT.zip)
> fix: ensure to get version 1.32.3 of gravitee-reporter-api

- src/main/resources/freemarker/es7x/mapping/index-template-v4-metrics.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-metrics.ftl
**Issue**
no issue related
- fix JSON syntaxe for ES7
- align mapping ES7/ES8
---
- use it directly by updating your project with version: `5.9.1-fix-additional-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/5.9.1-fix-additional-SNAPSHOT/gravitee-reporter-elasticsearch-5.9.1-fix-additional-SNAPSHOT.zip)
> fix: fix mapping

- README.adoc
- pom.xml
- src/main/resources/freemarker/es7x/mapping/index-template-v4-metrics.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-metrics.ftl
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
Support additional metrics
---
- use it directly by updating your project with version: `6.0.0-additional-metrics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.0.0-additional-metrics-SNAPSHOT/gravitee-reporter-elasticsearch-6.0.0-additional-metrics-SNAPSHOT.zip)
> Support additional metrics

- src/main/resources/freemarker/es8x/mapping/index-template-event-metrics.ftl
**Issue**
https://gravitee.atlassian.net/browse/APIM-10024
Added an index template to create v4 event native metrics time series index.
---
- use it directly by updating your project with version: `6.1.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metrics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.1.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metrics-SNAPSHOT/gravitee-reporter-elasticsearch-6.1.0-apim-10024-adapt-elasticsearch-reporter-to-han …
> feat: add an index template for v4 native event metrics

- pom.xml
- src/main/resources/freemarker/es7x/mapping/index-template-event-metrics.ftl
**Issue**
https://gravitee.atlassian.net/browse/APIM-10024
Added update template for ES7 index.
---
- use it directly by updating your project with version: `6.2.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metrics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.2.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metrics-SNAPSHOT/gravitee-reporter-elasticsearch-6.2.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metrics-SNAPSHOT.zip)
> feat: add an index template for v4 native event metrics in ES7

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/APIM-10024
bump gravitee-reporter-common version to 1.7.0-alpha.7
---
- use it directly by updating your project with version: `6.2.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metrics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.2.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metrics-SNAPSHOT/gravitee-reporter-elasticsearch-6.2.0-apim-10024-adapt-elasticsearch-reporter-to-handle-native-event-metri …
> chore: bump gravitee-reporter-common version to 1.7.0-alpha.7

- pom.xml
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es7/ES7IndexPreparer.java
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es8/ES8IndexPreparer.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-10629
Prepare index as data stream when metrics are to be saved as time series data stream.
---
- use it directly by updating your project with version: `6.2.0-apim-10629-error-when-starting-a-fresh-gateway-environment-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.2.0-apim-10629-error-when-starting-a-fresh-gateway-environment-SNAPSHOT/gravitee-reporter-elasticsearch-6.2.0-apim-10629-error-when-starting-a-fresh-gateway-environment-SN …
> feat: prepare index as data stream

- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es7/ES7IndexPreparer.java
- src/main/java/io/gravitee/reporter/elasticsearch/mapping/es8/ES8IndexPreparer.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-10629
These changes will exclude creation of an index alias when we use data streams.
---
- use it directly by updating your project with version: `6.2.0-apim-10629-error-when-starting-a-fresh-gateway-environment-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.2.0-apim-10629-error-when-starting-a-fresh-gateway-environment-SNAPSHOT/gravitee-reporter-elasticsearch-6.2.0-apim-10629-error-when-starting-a-fresh-gateway-environment-SNAPSHOT …
> feat: exclude creating index alias when using data streams

- .circleci/config.yml
Use latest version of gravitee-orb
---
- use it directly by updating your project with version: `6.0.3`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.0.3/gravitee-reporter-elasticsearch-6.0.3.zip)
> bump gravitee-orb

- src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-v4-metrics.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-request.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-metrics.ftl
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
A small description of what you did in that PR.
---
- use it directly by updating your project with version: `6.2.3-APIM-11027-es-indexing-error-bp-6-2-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/reporter/gravitee-reporter-elasticsearch/6.2.3-APIM-11027-es-indexing-error-bp-6-2-SNAPSHOT/gravitee-reporter-elasticsearch-6.2.3-APIM-11027-es-indexing-error-bp-6-2-SNAPSHOT.zip)
> fix: Elastic Index Error in V2 and V4 http proxy
